// folders types
export const HIDE_FOLDERS = "HIDE_FOLDERS"
export const ADD_FOLDER = "ADD_FOLDER"
export const DELETE_FOLDER = "DELETE_FOLDER"
export const PRESS_ADD_FOLDER_BTN = "PRESS_ADD_FOLDER_BTN"
export const PRESS_EDIT_FOLDER_NAME_BTN = "PRESS_EDIT_FOLDER_NAME_BTN"
export const CHANGE_FOLDER_NAME = "CHANGE_FOLDER_NAME"
export const SAVE_FOLDER_ID = "SAVE_FOLDER_ID"

// notes types
export const ADD_NOTE = "ADD_NOTE"
export const DELETE_NOTE = "DELETE_NOTE"
export const PRESS_ADD_NOTE_NAME_BTN = "PRESS_ADD_NOTE_NAME_BTN"
export const PRESS_EDIT_NOTE_NAME_BTN = "PRESS_EDIT_NOTE_NAME_BTN"
export const CHANGE_NOTE_NAME = "CHANGE_NOTE_NAME"
export const CHANGE_NOTE_BODY = "CHANGE_NOTE_BODY"
export const SAVE_NOTE_ID = "SAVE_NOTE_ID"

// common types
export const SAVE_SELECTED_ITEM_ID = "SAVE_SELECTED_ITEM_ID"
export const DELETE_SELECTED_ITEM = "DELETE_SELECTED_ITEM"
export const IS_DIALOG_OPENED = "IS_DIALOG_OPENED"
export const UPDATE_FOLDER_ALL = "UPDATE_FOLDER_ALL"
export const CHANGE_NOTE_BODY_IN_NOTES_IN_THIS_FOLDER =
  "CHANGE_NOTE_BODY_IN_NOTES_IN_THIS_FOLDER"
export const CHANGE_NOTES_IN_THIS_FOLDER = "CHANGE_NOTES_IN_THIS_FOLDER"
export const CHANGE_NOTE_NAME_IN_NOTES_IN_THIS_FOLDER =
  "CHANGE_NOTE_NAME_IN_NOTES_IN_THIS_FOLDER"
export const DELETE_NOTE_IN_NOTES_IN_THIS_FOLDER =
  "DELETE_NOTE_IN_NOTES_IN_THIS_FOLDER"
export const DELETE_NOTE_IN_NOTES_IN_THIS_FOLDER_ON_DRAG_END =
  "DELETE_NOTE_IN_NOTES_IN_THIS_FOLDER_ON_DRAG_END"
